apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:I/t51wccJSPTgT89otTvSfRGU2VV2w0OVQ7y/JN78ZAxDq+t,iv:xuc9DCXnJ2Sw8RpkRaQ3nH2L4jFLLaFTfGNOENB3B3k=,tag:N6nvCyvqWulukcRyGIA6cQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:xNcB3uf/WBfS+yrr6gi0htHZFzaS7rdfIxrx4QjZWr97ZYO3bsWyjd2VtfVLCOuPUTyAqIH+VLAhQ+hMkF6s5p6xvBz1r1/YZo5KVGnLREychCcjT5ha9+7SzdLi24AXFcOZQgvEKvdfbEGE2qL8Tvobww8uta0yfncimcjKSXyNpycTDt/Mp/bYSfByVGIisUWFAfsk76t6oy/vAfFIVkzB9YfcV66Xp14WlTvPaA==,iv:2Xx6FTzBZSaO4z7QyyOK1QIGjSv+vHPoIdmhmt/j7KU=,tag:kftlWQrC8xjc468Ld4DXsw==,type:str]
sops:
    age:
        - recipient: age1nclhqyczqg4y063zv0r8umpnx07fdvffluvfx3ylkz5jl9asw3ts38vpnl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcGNRTTRxMFA0Q1ZkSXh5
            TW4wMTNsMVhDY1dnZzkvazNDbjFEVEEzRnhZCis0Z00rdjkwdkl6dS8zZnROa3J2
            MFduUHZNS1lMMzBCYUxxT1EyS2xiQ2MKLS0tIENxTzN0ZjRtM1N0b0xIblNOTC9w
            SWZuT0d0YUVSaTlhRUN6V1Rla1pSdHMKOzIgfGJHcO9unTLJy3RdV1DkvNqs3x3r
            PQqLaAchrVIbI0fWHO2hQndrMaP9OMUyHB4uLzKXEbCJ649ccI4OpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T05:44:51Z"
    mac: ENC[AES256_GCM,data:4oZXTI8MZGBOtDHiCJTS7+XvBFDyUv5uHppZtzoiqHOQHKeZ53yDynjzca5f6Ni4oFUhN6gi26M7h+2cQrOzlyMIhCrVeFYbO1uhMIpGRl5dxw6Ym7WjgfXM2oFcGAP+p5WYxJwD3oxgQ9VEmoTG1RmP6BPTyBfRC/AIj1oUeFs=,iv:BzFiJDbFMJ8rC6+paQur+i2rKSVT5tCSemk1fCdfWhU=,tag:VCIzuLDyiLA5RqRYyREWsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
