apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Tly5duFi6Sv9CZnaCZZnZkXmdPX1jK40ZQgVnmYOzOBzK+vo,iv:KrG1lIIxW850yjxBznqOhubur0JEWGH1nvyLICkxGJc=,tag:bHi4eIiZueez3fkNxa8ZUQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:gA++3L8Nl5ubG0VcGVcDwaEIigM21s3HlpNJPLh0P8BA+Bq+y7zFBoUUanhrKXfjIJ9VIWZ90iAUFw+4CgWwbQztufyziuOvzqqDvT3IcXmp5k+z2uvi8daqrySD1mcZfx4+5d5nG3jcf00vSEILNn72ndbqzWlPOd6CnmKv5bpXDT6VZhMZnM+PTbr7kxPFaArXy5/1kQSNSWOccGo34ZX9KWq0xycdSeyu635kNQ==,iv:ti0VylwjKoVHp4vRC1S+NVkOLEYILrgpKKjId4wja7g=,tag:sdxOttYlk7c2AUxZDZIkGQ==,type:str]
sops:
    age:
        - recipient: age1nclhqyczqg4y063zv0r8umpnx07fdvffluvfx3ylkz5jl9asw3ts38vpnl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NUtLWThPRi9jMFcxNTI4
            WUpGaWk5SkZsOS9aSmI0a3BvWS85bTE1anhBClhyV0FxSW1HM3pLaXpOUlowOEgr
            OUxaNXpua2JGeFNsZDhkaXZiZTFDbXcKLS0tIGlGMnZCamc2czlyR1ZsQnVySXpU
            TGlsdnczQ2tjM2NjY2xzY3lVSVhYVlEKaJaZo/xBwtJY/fiyhwStyppgxlKeCEyO
            b/7G+TuA7m9/VrUNKZN8dmVRiDeA0v/cUb+svEy1iogCjqvMBGCYgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T01:45:17Z"
    mac: ENC[AES256_GCM,data:3bTi2d6gntrQWcGckh45m0QyZ9tJ1gl/VX6Z1ozRU67RDFHwalIYFQ6YYRamfPcSeDSQnWQdZ14jUkd4lD4H9RkoPQw/GegvsL7dDeE15oSdNxHLUjWI/OlcQr5RdtmNrv01NgNG/EydGs3QvspA2MYVSX8Euv2z6i/XAfgwp3A=,iv:We+w5SREf7n080qE6OPMTbe51OMM0VH1D4pwyHiESpY=,tag:Y5Gw3cmxoAjsQOE62N91mw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
