---
kubernetes:
  children:
    controllers:
      hosts:
        "nano-sv":
          ansible_user: "maez"
          ansible_host: "192.168.0.207"
          ansible_ssh_private_key_file: ~/.ssh/github_ed25519
