apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:/Cb33D+/Os4nY6yTaHd9Y9qyATKlUSOQnjiTlTa+6a5Xc7WhV3C6Dg==,iv:sM9b1unUDpZAVErItVheZgm8+dycUubwT6+WqaSYCbc=,tag:nsZbcbYvg8yTWdD7Y4+p7g==,type:str]
sops:
    age:
        - recipient: age1nclhqyczqg4y063zv0r8umpnx07fdvffluvfx3ylkz5jl9asw3ts38vpnl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTVYrdlZGY2NHWGo3U2Vh
            RXhFd25oMXlpcjRZajlPV1ZmTFdZS1hWSFhNCmxVVUM3ektvRjNOQVFGUHRQbVpa
            M3BIWkYrcUU5MS9lZW1LY3R6em9CMTQKLS0tIE8zNU9KSnR5bzhxcWFWOUx0a0VW
            VFVMOGNkeFRtMUtVL1RyZTJEVjBpRTgKlipfXT695ZShN1fd1UM6jLOuNcjnRD5N
            ztn53RAa5G0balx7D8Cin7zXteFPFjvdUhUfybiXpDGlPPzyxOguZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T05:44:51Z"
    mac: ENC[AES256_GCM,data:JyLmAlek2XQty3zyVHL4kHVemvgCA/vWNiMVsXuVFUSqnefUMKHM1EaoFw9NfwkqhwDh2YST/p6M+uH9grwfQMojIJajuMH7KRQ5SUKg/aJP96nDzaDykqSSD0/O0U5YQCHAZ2ceYhhdMoW50b1OnwkRh/Cq7qJvAvEigp/xdqg=,iv:Q0XKHYdul8qIMJot/MbrUSg5NsNDe4J30B8l/jmcxyg=,tag:vT4TmJde1VbMsOn48mTpag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
