apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:RFo7GixG7/qGlo+hu/8M1FpDNsdsft5+ktS7r/aEJMYiC31fbkYJbg==,iv:HWr+8jCUuZjqPH8bfe3Wg7y+9iXaS3A9ZjI/Oy6R3pg=,tag:suS6vGsWmNS9HBspH87z0g==,type:str]
sops:
    age:
        - recipient: age1nclhqyczqg4y063zv0r8umpnx07fdvffluvfx3ylkz5jl9asw3ts38vpnl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOW5Vd1JXRi9PYmQ5Z0xv
            ckROeTN6dG1QdzB2NjViNVJWbjE5amphYm13CkhoUmlYdnVQeG9mL1VlWUdnMHVu
            SUx6Q21jS3M0VG0wTzJ4dmM2aGdwaDAKLS0tIEZDSU45Tjlqb0ZXQm1ZYjVFOXBr
            a1FDR2tjV0ZoUzJGUVdUeXcxenJ1ZlEKkldjuaJ5/KLMcQiKYB98TVaLZJYJtq9v
            dKtiG7K1LyTIH3KOwBb3EVxVJxWzyyJkUy1WK8fc6R2VffoUiAAeZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T06:11:35Z"
    mac: ENC[AES256_GCM,data:/vTQzw4yOA13GgAqe8VTRbL/vUvMM+Mta4pt3UGujwTiKW34lTVdYRCEwZ5zt3gCD7BwvHzFQ/9KKstkqvS0gLxHEgOz8Q6itB6YkEE2sZo8e0kEQkVnvg8DoMhePoC5U5oJHNb8rJD8DBVJtl2QIsDvQinXSI99A5Maf1ASXlU=,iv:ZIlrWP/tGG4v6OCMB6alQoVQk8GoRvmAZZ8oqfooZaI=,tag:NYvdkWkuVCfUOSseAD1yzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
