---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitea-secret
    template:
      engineVersion: v2
      data:
        # Auth Config
        GITEA__security__SECRET_KEY: "{{ .GITEA_SECURITY_KEY }}"
        GITEA__admin__USERNAME: "{{ .GITEA_ADMIN_USERNAME }}"
        GITEA__admin__PASSWORD: "{{ .GITEA_ADMIN_PASSWORD }}"
        GITEA__admin__EMAIL: "{{ .GITEA_ADMIN_EMAIL }}"
        # Database Config
        GITEA__database__HOST: &dbHost postgres17-rw.database.svc.cluster.local
        GITEA__database__NAME: &dbName "{{ .GITEA_DB_NAME }}"
        GITEA__database__USER: &dbUser "{{ .GITEA_DB_USER }}"
        GITEA__database__PASSWD: &dbPass "{{ .GITEA_DB_PASS }}"
        # Mail Config
        GITEA__MAILER__ENABLED: "True"
        GITEA__MAILER__PROTOCOL: "SMTPS"
        GITEA__MAILER__SMTP_ADDR: smtp.gmail.com
        GITEA__MAILER__SMTP_PORT: "465"
        GITEA__MAILER__FROM: "{{ .GITEA_MAIL_FROM }}"
        GITEA__MAILER__USER: "{{ .GITEA_MAIL_USER }}"
        GITEA__MAILER__PASSWD: "{{ .GITEA_MAIL_PASSWD }}"
        GITEA__security__SKIP_TLS_VERIFY: "True"
        # Database INIT
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: gitea
    - extract:
        key: cloudnative-pg
