---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gitea
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  targetNamespace: storage
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  # valuesFrom:
  #   - targetPath: controllers.gitea.containers.gitea.env.GITEA__database__PASSWD
  #     kind: Secret
  #     name: gitea-config
  #     valuesKey: POSTGRESQL_PASSWORD
  values:
    fullnameOverride: *app
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      gitea:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.4.0@sha256:a9f405688344a8a6f718e2c344438342ad21540986aeb5ab5fa781831eb2c597
            envFrom: &envFrom
              - secretRef:
                  name: gitea-secret
        containers:
          app:
            image:
              repository: docker.gitea.com/gitea
              tag: 1.23.7-rootless
            env:
              TZ: "${TIMEZONE}"
              USER_UID: 1000
              USER_GID: 1000
              GITEA__ACTIONS__ENABLED: "True"
              GITEA__database__DB_TYPE: "postgres"
              GITEA__REPOSITORY__ENABLE_PUSH_CREATE_USER: "True"
              GITEA__REPOSITORY__DEFAULT_BRANCH: "main"
              GITEA__SECURITY__INSTALL_LOCK: "True"
              GITEA__SERVER__DOMAIN: "git.${SECRET_DOMAIN}"
              GITEA__SERVER__ROOT_URL: "https://git.${SECRET_DOMAIN}"
              GITEA__SERVER__SSH_DOMAIN: "ssh.git.${SECRET_DOMAIN}"
              GITEA__SERVER__SSH_PORT: 22
              GITEA__SERVER__LFS_START_SERVER: "True"
              GITEA__service__DISABLE_REGISTRATION: "True"
              # GITEA__log__MODE: "console"
              # GITEA__log__LEVEL: "debug"
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              # mkdir: can't create directory '/tmp/gitea': Read-only file system
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 300Mi
              limits:
                memory: 600Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000
      ssh:
        enabled: true
        type: LoadBalancer
        controller: *app
        externalTrafficPolicy: Cluster
        loadBalancerIP: 192.168.0.205
        ports:
          ssh:
            enabled: true
            port: 22
            targetPort: 2222
            protocol: TCP
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        className: external
        hosts:
          - host: "git.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        existingClaim: gitea
        globalMounts:
          - path: /var/lib/gitea
      tmpfs:
        enabled: true
        type: emptyDir
        advancedMounts:
          gitea:
            app: &tmpdirs
              - path: /tmp/gitea
                subPath: gitea
                readOnly: false
            chown-tmpdirs: *tmpdirs
