---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: storage
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
