---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: gitea
spec:
  storageClassName: ${DEFAULT_STORAGE}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
