apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:nwiQOyYnpxxmQUBoug0=,iv:VIUbISxo61wwaUmPGFRTG7ggkhwKIWiGkaFqG43kjs8=,tag:+BoPHHkRns/ft1no8sQSLg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:dBQEpZnc91JibaIn5GDn1RF1iA==,iv:eTTzg/ikAQZIBjkkOFcPlVlXSf2HX62jQ6il3UL/7yQ=,tag:lYDNKXNuPn8zuHnM4mg38w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xJZ7dyOHsvaQLmbrheXRbucF5ZwDjL7dIvIGUkOYcb0Tvy0q,iv:VpSCX/J+nn13FDD0oJqWEBu5J6vSgUdLZeGCjZ7HoIQ=,tag:BXNxaZVdSLH8/meUmpbwgw==,type:str]
sops:
    age:
        - recipient: age1nclhqyczqg4y063zv0r8umpnx07fdvffluvfx3ylkz5jl9asw3ts38vpnl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYmVhTkx6dkdFd0k2cng1
            d290R1p0czlmR1dUazMreVVMWnNISERONFJBCjNRUmt2NUNpNDRtbHV5eHBQdFRV
            eGQwZldkUm1tdmhKdXBmajYvdzhZN1kKLS0tIENDRVdrMlczeXhVdm52d3JucFpO
            bzJocm5ETmpvaXFYNm96cFpXbEl5SEUK4wwaNmZaV+UyyaSU9uSUe+1OYQOEhFxN
            yqrG3O8WdkeeKi9GNhpCVEHygx54ihRZxrLrvQcxTPWRxt44Nbk05A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T03:45:02Z"
    mac: ENC[AES256_GCM,data:PPF/X7hpLBBIYQ+dIHJDKQwfYc0nUyIecppeT4tXxVtkRUwBKYMXtVOcK+DN/H115Vq5bWiu9j29d2feA761oIFTClNto6V4YrZHiOMC744jcE59/6z8x0yFgI1bF/apMvdJ+DNpHjs0QNjxBRRG7bCm20FyBbao8gkEalAXAcM=,iv:TYWAIqSYcTqejeUIGl+Q7+xP9v1sBl7ZxL4rOx6ZtFA=,tag:UdLs4CM+rt/3p8TbGA4pkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
