apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:I0QTnjGKR5k5YHp4knwkrTXKCIKIE/uk7qA4466apDQ=,iv:YnuS3LDd+1zNR2GH5SV0UB3laz8cutn1CBaTWpSjAuM=,tag:JO4kaTtoSCYBVX1Dmkjm5Q==,type:str]
sops:
    age:
        - recipient: age1nclhqyczqg4y063zv0r8umpnx07fdvffluvfx3ylkz5jl9asw3ts38vpnl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZElET0ZWc1B1LzY4MFp5
            N1duQU1jTEx0TS9ZSTdIaXJZN0lJMlhBczF3Cm05RTlOTkhiZ1hNa3lxOFpRcm14
            SjJaNlpqKzNIQXc3SUZoVEtmZk1Dd1kKLS0tIDhkWjhOaTlvQWVyRzVabGFvN3dZ
            R3VvL1VlQ2FZclh0U0FBSnl1MFJ1SlEKvicMwKaGsZcGFOY6zRpDrlkz3++SlLnc
            Bi+Ur0/0etFVPHyB6kPNHE3g5kf8MlVZ7z3BihKMrAHp+3OI+i1u0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T05:44:51Z"
    mac: ENC[AES256_GCM,data:lBLPkOgaeiQUWtiAAdyyHbxEojXbIymFlxKsIqJDE1eOsrrFTG4ELk3D29jMaFAgr0w2lZufThJzVjlEseZpSi//2TWVRBJDGi65La/cKYKNaQFadkT7OEQGm3AYeGb/wuFoq0IDlrWdHDCCc7aVf38L7IbD7+Q30KD4JO5FiM8=,iv:B7D9DeF22wqIPCgM8jMG5wMUQsqZW2p9KCfAn4HTVcs=,tag:DgmQcpqdUNl2atamqfT3Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
