apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:R9wNkr/WEiCL00/FxfRmlDK+EAod37kr68K/9r37uI8=,iv:1wXFBJGn3BGi9gBKG2VpscHef7a/YSaQ2IOnyqUBW1c=,tag:B2DOOvM26xEZ+ctEfrqqCg==,type:str]
sops:
    age:
        - recipient: age1nclhqyczqg4y063zv0r8umpnx07fdvffluvfx3ylkz5jl9asw3ts38vpnl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YU5UOUJLWE5QZ2VOeHdm
            Q3dmeXhscW5MaVpvMlRJdTVWQTE0TGtZT2xRCnFoMXdVMmd6RHhrWjh1SmJYdFd1
            UjdYaUplTHJvWEc2VCtKZDB6RXdFamcKLS0tIGlBekNkR0pJY2ZJYW1XZDh2NWlI
            enNYdk83eEdkZm9OTlJac3ViYWxZcm8KoDAHSCjy1VTp1qXjVIT2ySnncg55rHOT
            g4pWs1NpkMx4Cp/0e9ib8vYDe61RVs/8hVvvHLCKmY9hp7wdRYQYqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T06:11:35Z"
    mac: ENC[AES256_GCM,data:SQgFuqgtrMueTbAZVEnHxDyz7gS8BkWfQI8eTYwtAYjUYYyy1nSmoc31P9h5Wa50g4zM2uk/5xI3rp3ESygqCk/x8pG1ll3v7nP3x2er1wtZ9ul8OIDv9T10R/Bg9LbBD3xxSOZnxbos2vqGvMDaipKY1EZa09K/DVjio8S1Who=,iv:0iLHteylYCxk71JIHcHd8YOEvFHsS5I8txmVmJduG/M=,tag:EVL+PgAHhXM/ac8EWLibiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
