---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name gitea
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  targetNamespace: gitea
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  valuesFrom:
    - targetPath: controllers.gitea.containers.gitea.env.GITEA__database__PASSWD
      kind: Secret
      name: gitea-config
      valuesKey: POSTGRESQL_PASSWORD
  values:
    fullnameOverride: *name
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      gitea:
        containers:
          gitea:
            image:
              repository: docker.gitea.com/gitea
              tag: 1.23.7-rootless
            env:
              TZ: "${TIMEZONE}"
              USER_UID: 1000
              USER_GID: 1000
              GITEA__ACTIONS__ENABLED: "True"
              GITEA__database__DB_TYPE: "postgres"
              GITEA__database__HOST: "gitea-postgres-v17-rw.gitea.svc.cluster.local:5432"
              GITEA__database__NAME: "${gitea_db_creds}"
              GITEA__database__USER: "${gitea_db_creds}"
              GITEA__MAILER__ENABLED: "True"
              GITEA__MAILER__PROTOCOL: "SMTP"
              GITEA__MAILER__SMTP_ADDR: "exim.mailrelay.svc.cluster.local"
              GITEA__MAILER__SMTP_PORT: "25"
              GITEA__MAILER__FROM: "gitea@${SECRET_DEFAULT_DOMAIN}"
              GITEA__REPOSITORY__ENABLE_PUSH_CREATE_USER: "True"
              GITEA__REPOSITORY__DEFAULT_BRANCH: "main"
              GITEA__SECURITY__INSTALL_LOCK: "True"
              GITEA__SERVER__DOMAIN: "gitea.${SECRET_DEFAULT_DOMAIN}"
              GITEA__SERVER__ROOT_URL: "https://gitea.${SECRET_DEFAULT_DOMAIN}"
              GITEA__SERVER__SSH_DOMAIN: "ssh.${SECRET_DEFAULT_DOMAIN}"
              GITEA__SERVER__SSH_PORT: 22
            securityContext:
              allowPrivilegeEscalation: false
              # mkdir: can't create directory '/tmp/gitea': Read-only file system
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 300Mi
              limits:
                memory: 600Mi
    service:
      gitea:
        controller: *name
        ports:
          http:
            port: 3000
      ssh:
        enabled: true
        type: LoadBalancer
        controller: *name
        externalTrafficPolicy: Local
        loadBalancerIP: 10.0.1.34
        ports:
          ssh:
            enabled: true
            port: 22
            targetPort: 2222
            protocol: TCP
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths: &paths
              - path: /
                service:
                  identifier: app
                  port: http
      tailscale:
        enabled: true
        className: tailscale
        hosts:
          - host: &app "{{ .Release.Name }}"
            paths: *paths
        tls:
          - hosts:
              - *app
    persistence:
      config:
        enabled: true
        existingClaim: gitea
        globalMounts:
          - path: /var/lib/gitea
